version: "2.1"
services:
  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki:latest
    container_name: dokuwiki2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/rafrojas/dokupodstore:/config/dokuwiki/data
    ports:
      - 8080:80
    restart: unless-stopped
